version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node-sass
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react
    versions:
    - 16.14.0
