export default [
  { idx: 0, value: 'blinded', label: 'Blinded', icon: 'fas fa-eye-slash', color: 'black' },
  { idx: 1, value: 'bleeding', label: 'Bleeding', icon: 'fas fa-tint', color: 'red' },
  { idx: 2, value: 'burning', label: 'Burning', icon: 'fas fa-fire', color: 'darkorange' },
  { idx: 3, value: 'charmed', label: 'Charmed', icon: 'fas fa-heart', color: 'blueviolet' },
  { idx: 4, value: 'deafened', label: 'Deafened', icon: 'fas fa-deaf', color: 'grey' },
  { idx: 5, value: 'exhausted', label: 'Exhausted', icon: 'fas fa-bed', color: '#ca542e' },
  { idx: 6, value: 'frightened', label: 'Frightened', icon: 'fas fa-exclamation-triangle', color: '#f7cc57' },
  { idx: 7, value: 'grappled', label: 'Grappled', icon: 'fas fa-lock', color: 'black' },
  { idx: 8, value: 'incapacitated', label: 'Incapacitated', icon: 'fas fa-wheelchair', color: 'darkblue' },
  { idx: 9, value: 'invisible', label: 'Invisible', icon: 'fas fa-low-vision', color: 'grey' },
  { idx: 10, value: 'other', label: 'Other', icon: 'fas fa-dice-d20', color: 'black' },
  { idx: 11, value: 'paralyzed', label: 'Paralyzed', icon: 'fas fa-dizzy', color: 'brown' },
  { idx: 12, value: 'petrified', label: 'Petrified', icon: 'fas fa-user-slash', color: 'brown' },
  { idx: 13, value: 'poisoned', label: 'Poisoned', icon: 'fas fa-skull-crossbones', color: 'green' },
  { idx: 14, value: 'prone', label: 'Prone', icon: 'fas fa-bed', color: 'black' },
  { idx: 15, value: 'restrained', label: 'Restrained', icon: 'fas fa-lock', color: 'maroon' },
  { idx: 16, value: 'stunned', label: 'Stunned', icon: 'fas fa-star', color: 'cornflowerblue' },
  { idx: 17, value: 'unconscious', label: 'Unconscious', icon: 'fas fa-procedures', color: 'darkblue' }
];
